---
- name: Check if role exist
  ansible.builtin.stat:
    path: roles/ansible_role_default_generic
  delegate_to: localhost
  register: path_ansible_role_default_generic

- name: No role ansible_role_default_generic  # noqa ignore-errors
  ansible.builtin.fail:
    msg: "roles/ansible_role_default_generic not found so don't run that role"
  failed_when: not path_ansible_role_default_generic.stat.exists
  ignore_errors: true

- name: Include role - ansible_role_default_generic
  ansible.builtin.include_role:
    name: ansible_role_default_generic
  when: path_ansible_role_default_generic.stat.exists
...
