---
- name: Check if role exist
  ansible.builtin.stat:
    path: roles/ansible-default-generic
  delegate_to: localhost
  register: role_ansible_cloud_init

- name: No role ansible-default-generic found  # noqa ignore-errors
  ansible.builtin.fail:
    msg: "roles/ansible-default-generic not found so don't run that role"
  failed_when: not role_ansible_cloud_init.stat.exists
  ignore_errors: true

- name: Include role - ansible-default-generic
  ansible.builtin.include_role:
    name: ansible-default-generic
  when: role_ansible_cloud_init.stat.exists
...
